define(["jquery"], function($) {

    const data = [
        {
            id: 0,
            word: 'customer',
            category: 'noun',
            hint: 'a person who buys goods or services from a shop or business.',
        },
        {
            id: 1,
            word: 'study',
            category: 'noun',
            hint: 'the time devoted by a particular person to gaining knowledge of an academic subject, typically at school, college, or university.',
        },
        {
            id: 2,
            word: 'opinion',
            category: 'noun',
            hint: 'a view or judgement formed about something, not necessarily based on fact or knowledge.',
        },
        {
            id: 3,
            word: 'government',
            category: 'noun',
            hint: 'the group of people with the authority to govern a country or state; a particular ministry in office.',
        },
        {
            id: 4,
            word: 'history',
            category: 'noun',
            hint: '',
        },
        {
            id: 5,
            word: 'literature',
            category: 'noun',
            hint: '',
        },
        {
            id: 6,
            word: 'knowledge',
            category: 'noun',
            hint: '',
        },
        {
            id: 7,
            word: 'society',
            category: 'noun',
            hint: '',
        },
        {
            id: 8,
            word: 'temperature',
            category: 'noun',
            hint: '',
        },
        {
            id: 9,
            word: 'community',
            category: 'noun',
            hint: '',
        },
        {
            id: 10,
            word: 'management',
            category: 'noun',
            hint: '',
        },
        {
            id: 11,
            word: 'equipment',
            category: 'noun',
            hint: '',
        },
        {
            id: 12,
            word: 'strategy',
            category: 'noun',
            hint: '',
        },
        {
            id: 13,
            word: 'university',
            category: 'noun',
            hint: '',
        },
        {
            id: 14,
            word: 'success',
            category: 'noun',
            hint: '',
        },
        {
            id: 15,
            word: 'moment',
            category: 'noun',
            hint: '',
        },
        {
            id: 16,
            word: 'medicine',
            category: 'noun',
            hint: '',
        },
        {
            id: 17,
            word: 'ambition',
            category: 'noun',
            hint: '',
        },
        {
            id: 18,
            word: 'lion',
            category: 'animal',
            hint: 'a large tawny-coloured cat that lives in prides, found in Africa and north-western India. The male has a flowing shaggy mane and takes little part in hunting, which is done cooperatively by the females.',
        },
        {
            id: 19,
            word: 'ostrich',
            category: 'animal',
            hint: 'a flightless swift-running African bird with a long neck, long legs, and two toes on each foot. It is the largest living bird, with males reaching a height of up to 2.75 m.',
        },
        {
            id: 20,
            word: 'giraffe',
            category: 'animal',
            hint: '',
        },
        {
            id: 21,
            word: 'bear',
            category: 'animal',
            hint: '',
        },
        {
            id: 22,
            word: 'zebra',
            category: 'animal',
            hint: '',
        },
        {
            id: 23,
            word: 'panda',
            category: 'animal',
            hint: '',
        },
        {
            id: 24,
            word: 'monkey',
            category: 'animal',
            hint: '',
        },
        {
            id: 25,
            word: 'dog',
            category: 'animal',
            hint: '',
        },
        {
            id: 26,
            word: 'cat',
            category: 'animal',
            hint: '',
        },
        {
            id: 27,
            word: 'rabbit',
            category: 'animal',
            hint: '',
        },
        {
            id: 28,
            word: 'duck',
            category: 'animal',
            hint: '',
        },
        {
            id: 29,
            word: 'fox',
            category: 'animal',
            hint: '',
        },
        {
            id: 30,
            word: 'horse',
            category: 'animal',
            hint: '',
        },
        {
            id: 31,
            word: 'donkey',
            category: 'animal',
            hint: '',
        },
        {
            id: 32,
            word: 'dear',
            category: 'animal',
            hint: '',
        },
        {
            id: 33,
            word: 'snake',
            category: 'animal',
            hint: '',
        },
        {
            id: 34,
            word: 'frog',
            category: 'animal',
            hint: '',
        },
        {
            id: 35,
            word: 'crocodile',
            category: 'animal',
            hint: '',
        },
        {
            id: 36,
            word: 'tiger',
            category: 'animal',
            hint: '',
        },
        {
            id: 37,
            word: 'goat',
            category: 'animal',
            hint: '',
        },
        {
            id: 38,
            word: 'sheep',
            category: 'animal',
            hint: '',
        },
        {
            id: 39,
            word: 'owl',
            category: 'animal',
            hint: '',
        },
        {
            id: 40,
            word: 'bison',
            category: 'animal',
            hint: '',
        },
        {
            id: 41,
            word: 'sparrow',
            category: 'animal',
            hint: '',
        },
        {
            id: 42,
            word: 'kangaroo',
            category: 'animal',
            hint: '',
        },
        {
            id: 43,
            word: 'apple',
            category: 'fruit',
            hint: '',
        },
        {
            id: 44,
            word: 'grapes',
            category: 'fruit',
            hint: '',
        },
        {
            id: 45,
            word: 'orange',
            category: 'fruit',
            hint: '',
        },
        {
            id: 46,
            word: 'mango',
            category: 'fruit',
            hint: '',
        },
        {
            id: 47,
            word: 'banana',
            category: 'fruit',
            hint: '',
        },
        {
            id: 48,
            word: 'strawberry',
            category: 'fruit',
            hint: '',
        },
        {
            id: 49,
            word: 'cherry',
            category: 'fruit',
            hint: '',
        },
        {
            id: 50,
            word: 'guava',
            category: 'fruit',
            hint: '',
        },
        {
            id: 51,
            word: 'coconut',
            category: 'fruit',
            hint: '',
        },
        {
            id: 52,
            word: 'peach',
            category: 'fruit',
            hint: '',
        },
        {
            id: 53,
            word: 'pear',
            category: 'fruit',
            hint: '',
        },
        {
            id: 54,
            word: 'pineapple',
            category: 'fruit',
            hint: '',
        },
        {
            id: 55,
            word: 'cabbage',
            category: 'vegetable',
            hint: '',
        },
        {
            id: 56,
            word: 'cauliflower',
            category: 'vegetable',
            hint: '',
        },
        {
            id: 57,
            word: 'cabbage',
            category: 'vegetable',
            hint: '',
        },
        {
            id: 58,
            word: 'tomato',
            category: 'vegetable',
            hint: '',
        },
        {
            id: 59,
            word: 'onion',
            category: 'vegetable',
            hint: '',
        },
        {
            id: 60,
            word: 'potato',
            category: 'vegetable',
            hint: '',
        },
        {
            id: 61,
            word: 'spinach',
            category: 'vegetable',
            hint: '',
        },
        {
            id: 62,
            word: 'cucumber',
            category: 'vegetable',
            hint: '',
        },
        {
            id: 63,
            word: 'broccoli',
            category: 'vegetable',
            hint: '',
        },
        {
            id: 64,
            word: 'asparagus',
            category: 'vegetable',
            hint: '',
        },
        {
            id: 65,
            word: 'ToyStory',
            category: 'American Film',
            hint: '',
        },
        {
            id: 66,
            word: 'TheLionKing',
            category: 'American Film',
            hint: '',
        },
        {
            id: 67,
            word: 'FindingNemo',
            category: 'American Film',
            hint: '',
        },
        {
            id: 68,
            word: 'Shrek',
            category: 'American Film',
            hint: '',
        },
        {
            id: 69,
            word: 'BeautyandtheBeast',
            category: 'American Film',
            hint: '',
        },
        {
            id: 70,
            word: 'TheShawshankRedemption',
            category: 'American Film',
            hint: '',
        },
        {
            id: 71,
            word: 'TheDarkKnight',
            category: 'American Film',
            hint: '',
        },
        {
            id: 72,
            word: 'TheLordoftheRings',
            category: 'American Film',
            hint: '',
        },
        {
            id: 73,
            word: 'TheGodfather',
            category: 'American Film',
            hint: '',
        },
        {
            id: 74,
            word: 'Titanic',
            category: 'American Film',
            hint: '',
        },
        {
            id: 75,
            word: 'SpiderMan',
            category: 'American Film',
            hint: '',
        },
        {
            id: 76,
            word: 'HarryPotter',
            category: 'British Film',
            hint: '',
        },
        {
            id: 77,
            word: 'germany',
            category: 'country',
            hint: '',
        },
        {
            id: 78,
            word: 'france',
            category: 'country',
            hint: '',
        },
        {
            id: 79,
            word: 'spain',
            category: 'country',
            hint: '',
        },
        {
            id: 80,
            word: 'italy',
            category: 'country',
            hint: '',
        },
        {
            id: 81,
            word: 'portugal',
            category: 'country',
            hint: '',
        },
        {
            id: 82,
            word: 'switzerland',
            category: 'country',
            hint: '',
        },
        {
            id: 83,
            word: 'turkey',
            category: 'country',
            hint: '',
        },
        {
            id: 84,
            word: 'greece',
            category: 'country',
            hint: '',
        },
        {
            id: 85,
            word: 'norway',
            category: 'country',
            hint: '',
        },
        {
            id: 86,
            word: 'finland',
            category: 'country',
            hint: '',
        },
        {
            id: 87,
            word: 'sweden',
            category: 'country',
            hint: '',
        },
        {
            id: 88,
            word: 'denmark',
            category: 'country',
            hint: '',
        },
        {
            id: 89,
            word: 'iceland',
            category: 'country',
            hint: '',
        },
        {
            id: 90,
            word: 'greenland',
            category: 'country',
            hint: '',
        },
        {
            id: 91,
            word: 'unitedstatesofamerica',
            category: 'country',
            hint: '',
        },
        {
            id: 92,
            word: 'unitedkingdom',
            category: 'country',
            hint: '',
        },
        {
            id: 93,
            word: 'canada',
            category: 'country',
            hint: '',
        },
        {
            id: 94,
            word: 'newzealand',
            category: 'country',
            hint: '',
        },
        {
            id: 95,
            word: 'australia',
            category: 'country',
            hint: '',
        },
        {
            id: 96,
            word: 'mexico',
            category: 'country',
            hint: '',
        },
        {
            id: 97,
            word: 'china',
            category: 'country',
            hint: '',
        },
        {
            id: 98,
            word: 'japan',
            category: 'country',
            hint: '',
        },
        {
            id: 99,
            word: 'southkorea',
            category: 'country',
            hint: '',
        },
        {
            id: 100,
            word: 'russia',
            category: 'country',
            hint: '',
        },
        {
            id: 101,
            word: 'northkorea',
            category: 'country',
            hint: '',
        },
        {
            id: 102,
            word: 'indonesia',
            category: 'country',
            hint: '',
        },
        {
            id: 103,
            word: 'philippines',
            category: 'country',
            hint: '',
        },
        {
            id: 104,
            word: 'morocco',
            category: 'country',
            hint: '',
        },
        {
            id: 105,
            word: 'algeria',
            category: 'country',
            hint: '',
        },
        {
            id: 106,
            word: 'tunisia',
            category: 'country',
            hint: '',
        },
        {
            id: 107,
            word: 'kenya',
            category: 'country',
            hint: '',
        },
        {
            id: 108,
            word: 'maldives',
            category: 'country',
            hint: '',
        },
        {
            id: 109,
            word: 'pakistan',
            category: 'country',
            hint: '',
        },
        {
            id: 110,
            word: 'india',
            category: 'country',
            hint: '',
        },
        {
            id: 111,
            word: 'bangladesh',
            category: 'country',
            hint: '',
        },
        {
            id: 112,
            word: 'srilanka',
            category: 'country',
            hint: '',
        },
        {
            id: 113,
            word: 'afghanistan',
            category: 'country',
            hint: '',
        },
        {
            id: 114,
            word: 'iraq',
            category: 'country',
            hint: '',
        },
        {
            id: 115,
            word: 'yamen',
            category: 'country',
            hint: '',
        },
        {
            id: 116,
            word: 'saudiarabia',
            category: 'country',
            hint: '',
        },
        {
            id: 117,
            word: 'unitedarabemirates',
            category: 'country',
            hint: '',
        },
        {
            id: 118,
            word: 'bahrain',
            category: 'country',
            hint: '',
        },
        {
            id: 119,
            word: 'kuwait',
            category: 'country',
            hint: '',
        },
        {
            id: 120,
            word: 'syria',
            category: 'country',
            hint: '',
        },
    ]
    
    return data
})